# Generated by Django 5.2 on 2025-04-08 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('policy_number', models.CharField(primary_key=True, serialize=False)),
                ('coverage_type', models.CharField(choices=[('health', 'Health'), ('work', 'Work'), ('life', 'Life')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimsSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('claim_type', models.CharField(max_length=50)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='claims/docs/')),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('insurance_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance_api.insurancepolicy')),
            ],
        ),
    ]
