# Generated by Django 5.2 on 2025-04-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimssubmission',
            name='insurance_policy',
        ),
    ]
